# Generated by Django 4.2.16 on 2025-10-22 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livingarchive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cesiumpin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cesium Pin', 'verbose_name_plural': 'Cesium Pins'},
        ),
        migrations.AddField(
            model_name='cesiumpin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pins', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='cesiumpin',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cesiumpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='cesiumpin',
            name='height',
            field=models.FloatField(default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='cesiumpin',
            name='lat',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='cesiumpin',
            name='lon',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='cesiumpin',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='cesiumpin',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
